# ============================================================
# SESSION INIT — re-read all SunSystems source tables
# Run this if any NameError occurs on source variables
# ============================================================
tcurv  = safe_read(ref_path,    "TCURV")
tcurr  = safe_read(ref_path,    "TCURR")
tcurc  = safe_read(ref_path,    "TCURC")
tcurt  = safe_read(co_path,     "TCURT")
tcurx  = safe_read(co_path,     "TCURX")
t001   = safe_read(master_path, "T001")
t003   = safe_read(ref_path,    "T003")
t003t  = safe_read(ref_path,    "T003T")
t011   = safe_read(co_path,     "T011")
t093   = safe_read(co_path,     "T093")
t093b  = safe_read(co_path,     "T093B")
tka01  = safe_read(master_path, "TKA01")
csks   = safe_read(master_path, "CSKS")
cska   = safe_read(co_path,     "CSKA")
cskt   = safe_read(co_path,     "CSKT")
ska1   = safe_read(master_path, "SKA1")
skb1   = safe_read(master_path, "SKB1")
skat   = safe_read(master_path, "SKAT")
adrc   = safe_read(raw_base_root,"ADRC")
lfa1   = safe_read(raw_base_root,"LFA1")
lfb1   = safe_read(master_path, "LFB1")
lfm1   = safe_read(raw_base_root,"LFM1")
lfbk   = safe_read(raw_base_root,"LFBK")
bkpf   = safe_read(tx_path,     "BKPF")
bseg   = safe_read(tx_path,     "BSEG")
anla   = safe_read(master_path, "ANLA")
anlb   = safe_read(master_path, "ANLB")
anlc   = safe_read(pm_path,     "ANLC")
anlz   = safe_read(pm_path,     "ANLZ")
print("✅ All source tables re-read")